"""add Department

Revision ID: 616994834658
Revises: 89c45251e94f
Create Date: 2025-06-21 16:27:06.840838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616994834658'
down_revision = '89c45251e94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
